### ISSUE TITLE
Usecases: Criar Grupos

### ISSUE THREAD

**Issue by pahsantana** [ES-UFABC/Grupo-1-UniGether#17]
- [x] Criar entidades, modelos e classes (@pahsantana)
- [x] Configurar o socket.io(@pahsantana)
- [x] Criar rotas(@pahsantana)
- [x] Criar services(@guiPython)
- [x] Criar repository(@guiPython)
- [x] Criar migration(@pahsantana)
- [x] Criar tela para conversas(@pahsantana)
- [x] Integrar com backend(@pahsantana)
- [x] Corrigir bug no delete de grupos(@guiPython| @PaixaoThales)

**Comment by guiPython** [comment]
@pahsantana e @PaixaoThales, tive problemas com a rota de delete para grupos, mas as classes estão prontas.
