### ISSUE TITLE
Prototipagem das telas no Figma

### ISSUE THREAD

**Issue by guiPython** [ES-UFABC/Grupo-1-UniGether#9]
Prototipar  3 telas no Figma.

1. Pagina Home
2. Pagina de Login
3. Pagina de Cadastro

**Comment by guiPython** [comment]
Link Protótipo: https://www.figma.com/file/eJKy6eArnp86DHpdFqEVhD/ConectUni?node-id=47%3A106

**Comment by igorMilhomens** [comment]
2022-03-17  Realizado criação inicial do protótipo das 3 telas(Home, Cadastro e Login)

![image](https://user-images.githubusercontent.com/61119600/158915394-8563fcda-384b-451e-ad3f-cc11f3248923.png)

@biafreitasb O que acha? Podemos  avançar com a construção das telas?

Obs: Falta criar identidade para tela home (adicionar texto, e imagens)

**Comment by igorMilhomens** [comment]
O background usado foi o sugerido pela @biafreitasb  no grupo.

https://marcbruederlin.github.io/particles.js/
